const rental_products = [
  {
    name: 'Rusty looking side table in mahagony finish',
    image: '/images/side_table_multistyle_1-v2.jpg',
    description:
      'Green Earth brings you the sleek and stylish side table with teakwood finish',
    brand: 'Green Earth',
    category: 'Furniture',
    price: 6850.00,
    totalQuantity: 2,
    availableQuantity: 2,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'TVS Jupiter Bike 125CC',
    image: '/images/TVS_Jupiter-v2.jpg',
    description:
      'TVS Jupiter bike with the power of 125CC engine',
    brand: 'TVS',
    category: 'Bikes',
    price: 2200.00,
    totalQuantity: 2,
    availableQuantity: 2,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'Maruti New WagonR Petrol 1.2 Automatic',
    image: '/images/maruti_wagonr_new_auto-v2.jpg',
    description:
      'The cool new wagonr, revamped with the latest features',
    brand: 'Maruti',
    category: 'Cars',
    price: 4500.00,
    totalQuantity: 2,
    availableQuantity: 2,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'Tata Nexon XZA Plus Automatic',
    image: '/images/tata_nexon_xza_auto-v2.jpg',
    description:
      'The latest Tata Nexon with great security features',
    brand: 'Tata',
    category: 'Cars',
    price: 4800.00,
    totalQuantity: 1,
    availableQuantity: 1,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'Exquisite Olive Green lehenga with zardosi work',
    image: '/images/Lehenga_OliveGreen-v2.jpg',
    description:
      'Zoya brand - Exquisite Olive Green lehenga with zardosi work which makes you a star',
    brand: 'Zoya',
    category: 'Lehengas',
    price: 5999.99,
    totalQuantity: 10,
    availableQuantity: 10,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'Antique Neckpiece set - Jadau kundan',
    image: '/images/lotus_jadaukundan-v2.jpg',
    description:
      'Lotus design - unique and elegant - Jadau kundan neckpiece set',
    brand: 'LK',
    category: 'Jewellery',
    price: 5499.99,
    totalQuantity: 7,
    availableQuantity: 0,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'Exclusive sherwani - sizzling silver',
    image: '/images/sizzling_silver_sherwani_001-v2.jpg',
    description:
      'A sizzling sherwani in silver shade, which will light up the stage',
    brand: 'Zara',
    category: 'EthnicForMen',
    price: 7499.99,
    totalQuantity: 1,
    availableQuantity: 1,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'Tripod for DSLR camera',
    image: '/images/tripod1-v2.jpg',
    description:
      'Sleek and sturdy tripod with all basic features',
    brand: 'Digitek',
    category: 'Electronics',
    price: 1549.00,
    totalQuantity: 5,
    availableQuantity: 5,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'Canon EOS (DSLR) camera',
    image: '/images/Canon_DSLR_EOS-v2.jpg',
    description:
      'The perfect DSLR camera for you',
    brand: 'Digitek',
    category: 'Electronics',
    price: 1549.00,
    totalQuantity: 5,
    availableQuantity: 0,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  },
  {
    name: 'Maono XLR Podcast microphone',
    image: '/images/maono_xlr_podcast_microphone-v2.jpg',
    description:
      'The perfect microphone for all your content recordings',
    brand: 'JBL',
    category: 'Gadgets',
    price: 1800.00,
    totalQuantity: 2,
    availableQuantity: 2,
    refundableDeposit: 0.00,
    deliveryPickupCharges: 500.00,
    rentalPriceConfigurations: [],
  }
]

export default rental_products
